### ISSUE TITLE
Where is the Segmentation Net?

### ISSUE THREAD

**Issue by DeadWater1** [Srameo/DNF#3]

**Comment by Srameo** [comment]
DNF specializes in enhancing low-light images using raw data, which is why we do not offer a segmentation network. Additionally, by enhancing low-light images, there is a potential to improve the performance of segmentation networks, especially in low-light scenarios. We strongly encourage you to consider utilizing DNF as a pre-processing tool for tasks involving the segmentation of low-light scenes. If you achieve any results, please let us know!
